apiVersion: v1
baseDomain: <domain.name>
compute:
- hyperthreading: Enabled
  name: worker
  replicas: <no.of-workers>
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: <no.of-masters>
metadata:
  name: <cluster-name>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '<your-pull-secret>'
sshKey:  '<ssh-public-key>'
